version: '3.8'

services:
  
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
        - "5431:5432"
    environment:
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=keycloak
    volumes:
        - ./db-data/:/var/lib/postgresql/data
    container_name: postgresdb-comp3095-keycloak


  keycloak:
    image: jboss/keycloak
    restart: unless-stopped
    ports:
        - "8080:8080"
    environment:
        - DB_VENDOR=postgres
        - DB_ADDR=postgres
        - DB_DATABASE=keycloak
        - DB_USER=keycloak
        - DB_PASSWORD=password
        - DB_SCHEMA=public
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=password
    container_name: keycloak-comp3095
    depends_on:
        - postgres